### ISSUE TITLE
Add option to insert unformatted reference

### ISSUE THREAD

**Issue by maxmahlke** [jghauser/papis.nvim#10]
Hi again! I'm finally getting back to writing a paper and using `papis.nvim`. You've done a lot of work on this plugin, that's great!
I have had some issue/ideas for this plugin, I will open a series (edit: only two ideas, I figured out the two issues I had while writing their bug reports) of issues to discuss them :-) For the feature requests, I have some working code on my side, so if you agree that they make sense, I'm happy to open a PR.

First up: I would like the option to insert unformatted references, rather than having them formatted according to filetype. I use snippets a lot (eg `cp` and `ct` for `\citep{|}` and `\citet{|}` in `tex`) and don't need the formatting.

**Comment by jghauser** [comment]
Hey, happy to hear that! :) Yes, absolutely do open some pull requests. This seems like a sensible feature to implement.
