### ISSUE TITLE
Is there a good/better way to bridge bibtex/Zotero and papis? 

### ISSUE THREAD

**Issue by ThSGM** [jghauser/papis.nvim#103]
In essence, Zotero provide a good GUI for handling paper PDF management. However, what it does not do well is it does not provide the kind of CLI power that papis provides. The question is how do you use Zotero in conjunction with Papis. 

There is [one guide here](https://nicolasshu.com/zotero_and_papis.html) but it is clunky. The author is essentially suggesting for every single paper you own to be included within a titled folder where both the PDF can be housed, along with the info.yaml file that papis needs. 

But this will absolutely wreak your PDF/folder organisation. For example, I rely on being able to quickly find PDFs on my computer via a fuzzy-finder like Alfred. This would absolutely pollute your search tree, unless you specifically restricted it to only PDFs. Is there an alternative route to using papis in conjunction with Zotero and its PDF management?

**Comment by jghauser** [comment]
Hi @ThSGM! You're commenting in the `papis.nvim` repo (the repo about the neovim plugin for Papis), but it seems to me your comment is about Papis more generally. If so, I suggest opening a discussion [over there](https://github.com/papis/papis/discussions). If not, can you explain some more what exactly the relation to the `papis.nvim` plugin is?

More generally, there is a [`papis-zotero`](https://github.com/papis/papis-zotero) plugin for Papis that might be relevant to you. I guess the question is what exactly you're trying to achieve and whether maybe after getting used to Papis (and its Picker or webapp), you won't even need Zotero anymore. I at least ditched Zotero once I got used to Papis :D. If you don't want to do that, then maybe the `papis-zotero` plugin can do (some) of the things you want.

**Comment by ThSGM** [comment]
Thank you! 

Sorry you're right this was posted in the wrong group. I've made a post here: https://github.com/papis/papis/discussions/958

I think the main issue I have with ditching Zotero is that Zotero is the much more stable platform, which is almost certainly going to be continued to be maintained over the future. A solution method where your bibliography management is based off of Zotero firstly, but then linked to Papis is a much safer solution.
