### ISSUE TITLE
Enable multiple-selection in telescope picker

### ISSUE THREAD

**Issue by maxmahlke** [jghauser/papis.nvim#11]
I would like to be able to select more than one paper and insert multiple references into my document. I got this to work on my side: `<tab>` is used to mark entries in the picker (default), and hitting enter inserts the references separated by comma into the buffer. It's quite neat.

More difficult could be the integration of multiple references into the filetype-specific formatter function.

As said, if you think it makes sense, I'll open a PR.

**Comment by jghauser** [comment]
Uuuuh, this is actually something I've been thinking about myself. I'm personally more interested in opening multiple documents at the same time, which probably requires a little more work. Do open a pull request, and we can take it from there! Thanks!

**Comment by jghauser** [comment]
@maxmahlke, I've started working on this in #88 in case you want to give it a try :)
