### ISSUE TITLE
ps: illegal option -- q

### ISSUE THREAD

**Issue by jhvst** [jghauser/papis.nvim#23]
I get this problem when starting papis using this plugin which supposedly originates from here: https://github.com/jghauser/papis.nvim/blob/0e487d18690cd46ddc0ccfdfdfd3677b69e06128/lua/papis/utils.lua#L307

When I run `ps -q` I get an error saying `ps: illegal option -- q`. These are followed errors saying that my library files are faulty and will not be added to the database. As such, I see no files inside of neovim, even though the normal commands work fine.

I'm on Darwin version 13.5 Beta. I use Nix as my package manager, and even if I pull the `ps` command from Nix sources, I still get the same error.

**Comment by jghauser** [comment]
hey, thanks for the report! `ps -q`  needs to be run with some `pid`. can u grab (with `top` or something similar) some existing pid and try if `ps -q your_pid` also gives an error? i'm guessing the error has something to do with the mac (+ nix) setup, but i don't have a mac to test (i do run nixos though).

also, can you enable debugging (check config), and give the last few lines right when `papis.nvim` fails? although, i can see i didn't add any logging to that specific function, so it might not be too useful.

**Comment by jhvst** [comment]
```
juuso@darwin ~/G/nix-config (main)> ps
  PID TTY           TIME CMD
95209 ttys000    0:00.03 -fish
95215 ttys000    0:07.12 /nix/store/p5xh6az0cybf3k4a6h8f1m9hi6mj8n8v-alacritty-0.10.1/bin/alacritty
95216 ttys001    0:00.09 -fish
97109 ttys001    0:00.01 tmux
97237 ttys002    0:00.01 fish -c /nix/store/sdnm9p437fhjz9375x6f9lbb8gbig84y-reattach-to-user-namespace-2.9/bin/reattach-to-user-namespace -l /Users/juuso/.nix
97238 ttys002    0:00.06 -fish
97776 ttys002    0:00.11 /Users/juuso/.nix-profile/bin/vim --cmd lua vim.g.node_host_prog='/nix/store/rh05clpcwwxb5sh6r1sjz24k75vwbj1m-neovim-0.9.1/bin/nvim-no
98303 ttys003    0:00.02 fish -c /nix/store/sdnm9p437fhjz9375x6f9lbb8gbig84y-reattach-to-user-namespace-2.9/bin/reattach-to-user-namespace -l /Users/juuso/.nix
98304 ttys003    0:00.04 -fish
juuso@darwin ~/G/nix-config (main)> ps -q 95209
ps: illegal option -- q
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
juuso@darwin ~/G/nix-config (main) [1]>
```

```
papis: require("papis.health").check()

Sqlite database ~
- Papis.nvim db location: /Users/juuso/.papis/papis-nvim.sqlite3.
- OK The 'sqlite3' executable was found in path.
- OK The database exists.
- WARNING The database is empty.

File watcher ~
- ERROR No neovim instance is running file watchers.

```

**Comment by jhvst** [comment]
The debugging of the plugin does not display anything useful, because the `ps -q` error runs before it. I checked the very verbose logs of neovim, and it does not display anything that seems relevant here. What seems to be the problem is that on macOS, the `ps` command does not implement the `-q` option, so some alternative is needed there. The `-q` option does not exist on either the Apple provided system binary, or the one fetched from nixpkgs via `nix-shell -p ps` giving this hash (on unstable): `/nix/store/pzwjlikyq8wj792yy7hikpq6a1dnr4pq-ps-adv_cmds-119/bin/ps`.

**Comment by jhvst** [comment]
And for what it is worth, my nix-config is public, but I don't see anything here that would conflict with `ps`:
- darwin host: https://github.com/jhvst/nix-config/blob/main/hosts/darwin/default.nix
- neovim config: https://github.com/jhvst/nix-config/blob/main/home-manager/programs/neovim/default.nix

**Comment by jghauser** [comment]
Can you tell me what's the output of `ps -p some_pid`? It seems like that might be an alternative to `-q` that works on both linux and mac.

**Comment by jghauser** [comment]
nice, that looks useable! i just pushed a change, can you try it on your end and see if it work?

**Comment by jhvst** [comment]
Thank you, this error is seemingly fixed now! I still have a problem saying my .yaml files are faulty, but this seems unrelated to whatever was happening with ps.

Thanks again, I really appreciate it!

**Comment by jhvst** [comment]
Ah, the error was that the `yq` command on nixpkgs is the python version, which you say is not supported. I changed this to the go one and now all works great! Thanks again, excited to use the plugin for writing papers in vim :)

**Comment by jghauser** [comment]
Excellent, great to hear! Let me know if u find any other issues :)
