### ISSUE TITLE
Having issues with read_yaml function in papis-storage.lua

### ISSUE THREAD

**Issue by ckarren** [jghauser/papis.nvim#29]
I've been trying to install and config papis.nvim for a couple of days and am having issues when `:PapisStart` tries to add and convert yaml files. I know my install of yq is fine- I can run `yq -oj info.yaml` from the command line with no issue and it produces the correct json output. I know the function can find the yq executable, but it returns **nil**. I've saved the error from the yq golang code: `panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1366b55]` which makes me think that it can't find or read the yaml file. I don't know if this is an issue with the yq code or the papis-storage. Any suggestions?

**Comment by ckarren** [comment]
I've changed that line to: 
`local handler = io.popen(yq_bin .. ' -oj "' .. filepath:absolute() .. '" 2> NUL')` 
`NUL` is the Windows equivalent to `/dev/null` but that doesn't fix it.

**Comment by jghauser** [comment]
Thanks for trying that out! Does this command (with the `2> NUL`) work alright if you run it in the console? So something like `yq -oj "[ABSOLUTE_PATH_TO_FILE]" 2> NUL`? If so, then I think it's time we add some print statement in that function to figure out where things go wrong... :D
