### ISSUE TITLE
Entries are faulty

### ISSUE THREAD

**Issue by ZackGlenn** [jghauser/papis.nvim#31]
When papis.nvim initializes it gives me an error message like this for every entry in my database.
```
The entry at '/path/to/library/folder-name/info.yaml' is faulty and will not be added.
```

The info.yaml files all have the `papis_id` and `ref` fields, and `papis doctor` gives no errors, so I have no idea how the entries could be faulty.

**Comment by jghauser** [comment]
Hey, thanks for the report! If possible, could you share one of the `info.yaml` files? Also, just to make sure, you have the carrect `yq` installed (the `go` and not the `python` program, as indicated in the readme)?

**Comment by ZackGlenn** [comment]
Whoops, I definitely had the wrong `yq`. In my defense, arch treats the python version as the default. Everything is working fine now.
