### ISSUE TITLE
Setup not working correctly; database file apparently inaccessible

### ISSUE THREAD

**Issue by RobinTruax** [jghauser/papis.nvim#38]
Hi. I've been trying to set up `papis` and `papis.nvim` on my Windows machine for a day or two now, and I'm running into issues. `papis`, by this point, works fine sans a single warning message which seems to not impede the actual use of the system. I've tested the serve webapp and it behaves as expected. However, when I try to use `papis.nvim`, I continually run into the following error when trying to initialize it (either manually or by opening a markdown file, for example). Any idea what's going on here?

`Error executing lua callback: ...Data/Local/nvim-data/lazy/sqlite.lua/lua/sqlite
/defs.lua:709: sqlite.lua: couldn't connect to sql database, ERR: unable to open
 database file
stack traceback:
        [C]: in function 'error'
        ...Data/Local/nvim-data/lazy/sqlite.lua/lua/sqlite/defs.lua:709: in func
tion 'connect'
        ...ppData/Local/nvim-data/lazy/sqlite.lua/lua/sqlite/db.lua:162: in func
tion 'open'
        ...ppData/Local/nvim-data/lazy/sqlite.lua/lua/sqlite/db.lua:215: in func
tion 'run'
        ...pData/Local/nvim-data/lazy/sqlite.lua/lua/sqlite/tbl.lua:63: in funct
ion 'tbl'
        ...l/nvim-data/lazy/papis.nvim/lua/papis/sqlite-wrapper.lua:80: in main
chunk
        [C]: in function 'require'
        ...pData/Local/nvim-data/lazy/papis.nvim/lua/papis/init.lua:64: in funct
ion <...pData/Local/nvim-data/lazy/papis.nvim/lua/papis/init.lua:54>`

**Comment by jghauser** [comment]
I think I have an idea of what could be at fault, namely me not thinking of Windows paths :sweat_smile:. Can you try setting the `db_path` manually? I just realised (and as you can see in the README) that the default is a path with `/` in it, which I think won't work on Windows. If this fixes it, I will push a change to make it work for Windows too.

**Comment by jghauser** [comment]
Hi @RobinTruax, do you still have this issue?

**Comment by jghauser** [comment]
I'm closing this as #58 has re-implemented how papis.nvim handles paths. If the issue persists, feel free to re-open!
