### ISSUE TITLE
Dependency libyaml-dev

### ISSUE THREAD

**Issue by KMIJPH** [jghauser/papis.nvim#5]
I'm pretty sure `libyaml-dev` is a dependency in order to install `lyaml.`
When installing via packer, the installation of lyaml fails without giving any further information.
It would maybe be a good idea to mention it somewhere.

**Comment by jghauser** [comment]
Thanks for the feedback! I don't have `libyaml-dev` installed, though I think you might be right about the dependency on `libyaml` (which does exist on my system). Are you sure it's not that library?

I also see that `YAML` is mentioned in `external_dependencies` in [lyaml's rockspec](https://github.com/gvvaughan/lyaml/blob/master/lyaml-git-1.rockspec#L23). Not sure if packer is supposed to notify users about that.

**Comment by jghauser** [comment]
I've investigated this a bit and found some useful information in the README of [pubspec-assist.nvim](https://github.com/akinsho/pubspec-assist.nvim). I've included those instructions in the README here. I think this should fix this issue. If it doesn't, please feel free to re-open the issue. Thanks a lot for reporting!

**Comment by almirnunes** [comment]
Thanks, Joseph for opening the issue. I am on Fedora and had to install libyaml-dev to succeed with the lyaml installation. That wasn't clear to me just from the README. 

And thanks Julian for the plugin. I am excited to use it now.

Cheers.

**Comment by jghauser** [comment]
hey @almirnunes, thanks for the report! do you have to install `libyaml-dev` in addition to `libyaml`? Or is that package simply called `libyaml-dev` on Fedora?

**Comment by almirnunes** [comment]
> do you have to install libyaml-dev in addition to libyaml? 

libyaml was already installed. It seems to be present with Fedora by default. 

> Or is that package simply called libyaml-dev on Fedora?

It is actually called libyaml-devel. I installed it using the dnf package manager. After that the installation of lyaml succeded.
