### ISSUE TITLE
Missing log.lua?

### ISSUE THREAD

**Issue by davvil** [jghauser/papis.nvim#61]
When updating to the latest head (or relase 0.3.0), papis fails to load with message
```
.../share/nvim/lazy/papis.nvim/lua/papis/sqlite-wrapper.lua:8: module 'papis.log' not found:No LuaRocks module found for papis.log
```

Version 0.2.0 works (which uses `logger` instead of `log`).

**Comment by jghauser** [comment]
This is embarrassing, I forgot to add the new file :sweat_smile:. Fixed now in 0.3.1!
