### ISSUE TITLE
Problem with loading after v0.3.1

### ISSUE THREAD

**Issue by panosz** [jghauser/papis.nvim#62]
There seems to be some issue with pathlib:

```
...nosz/.local/share/nvim/lazy/papis.nvim/lua/papis/log.lua:12: module 'pathlib' not found:
    no field package preload['pathlib']
    cache_loader: module pathlib not found
    cache_loader_lib: module pathlib not found
        no file './pathlib.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/pathlib.lua'
        no file '/usr/local/share/lua/5.1/pathlib.lua'
        no file '/usr/local/share/lua/5.1/pathlib/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/pathlib.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/pathlib/init.lua'
        no file './pathlib.so'
        no file '/usr/local/lib/lua/5.1/pathlib.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/pathlib.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by jghauser** [comment]
Did you add pathlib to the dependencies? (It's a new dependency, see #1.)

I just realised that pathlib isn't actually needed in this file, so I'll remove it from there, but it's required elsewhere, so I'm pretty sure the error would just be triggered elsewhere.

**Comment by jghauser** [comment]
I've removed the requires in `log.lua`. Let me know what happens now :)

**Comment by panosz** [comment]
You mean in #446d937? Unfortunately it still persists

**Comment by jghauser** [comment]
Yes, that's the commit I meant. I'm a bit puzzled cause `pathlib` isn't required in that file anymore so there really isn't any way that it could fail to import it. Is the failure in a different file now (that's what I would expect to happen)? Are you sure that `pathlib` is actually installed and accessible? Maybe try `:lua require("pathlib")`, which would raise an error if it's not found. If there's an error, make sure that `pathlib` is added to your dependencies as mentioned in the README.

**Comment by jghauser** [comment]
Ok, my bad. Are you using `rocks.nvim`? I think I might have forgotten to add the dependency there. Fixing it now!

**Comment by panosz** [comment]
I am using `lazy.nvim`, but I hadn't realized that the dependencies had changed. Sorry for this. 

Everything works fine now, but I also had to add "nvim-neotest/nvim-nio" to the dependencies. I guess this is an issue with "pathlib.nvim" rather "papis.nvim" but I thought I'd mention it in case anyone else has the same problem.

**Comment by jghauser** [comment]
Oh right, that makes sense. pathlib.nvim requires nvim-nio and because plugins can't define their own dependencies, we need to do that. I'll update the readme. Thanks!
