### ISSUE TITLE
Papis startup fails

### ISSUE THREAD

**Issue by breneser** [jghauser/papis.nvim#67]
After installing Papis with `lazy.nvim` and configuring to load on markdown files, I get below error. None of the Papis commands are available, also telescope picker is not available to run.

Even if it is not lazy loaded, it still isn't working, but I don't see the following error if it is not lazy loaded.

```
Failed to run `config` for papis.nvim

...l/share/nvim/lazy/pathlib.nvim/lua/pathlib/utils/nuv.lua:60: bad argument #2 to '?' (number expected, got nil)

# stacktrace:
  - /pathlib.nvim/lua/pathlib/utils/nuv.lua:60 _in_ **mkdir**
  - /papis.nvim/lua/papis/sqlite-wrapper.lua:24
  - /papis.nvim/lua/papis/config.lua:223 _in_ **update**
  - /papis.nvim/lua/papis/init.lua:31 _in_ **setup**
  - /usr/share/nvim/runtime/filetype.lua:36
  - /usr/share/nvim/runtime/filetype.lua:35
```

Papis installation is as follows:

```
{
    "jghauser/papis.nvim",
    lazy = true,
    ft = "markdown",
    dependencies = {
      "kkharji/sqlite.lua",
      "MunifTanjim/nui.nvim",
      "pysan3/pathlib.nvim",
      "nvim-neotest/nvim-nio",
    },
    opts = {},
  }
```

**Comment by breneser** [comment]
Looks like a duplicate issue

**Comment by jghauser** [comment]
Hi @breneser! Thanks a lot for the report. There's a bug here that I've inadvertently introduced when moving to `pathlib.nvim`. I'll get back to you when it's fixed!

**Comment by jghauser** [comment]
This should fix it, if not feel free to re-open. Thanks again!
