### ISSUE TITLE
`get_ref_under_cursor` should fail gracefully if reference is not recognized

### ISSUE THREAD

**Issue by maxmahlke** [jghauser/papis.nvim#7]
If the reference under the cursor when running `:PapisOpenNote` is not in the expected format given the filetype, the `string.find` function below fails with the following traceback.

https://github.com/jghauser/papis.nvim/blob/5a1fc6cafcc601d983965a5899506a810f3ccdd1/lua/papis/cursor-actions/init.lua#L40

```
Error executing Lua callback: .../packer/opt/papis.nvim/lua/papis/cursor-actions/init.lua:40: malformed pattern (
missing ']')                                                                                                     
stack traceback:                                                                                                 
        [C]: in function 'find'                                                                                  
        .../packer/opt/papis.nvim/lua/papis/cursor-actions/init.lua:40: in function 'get_ref_under_cursor'       
        .../packer/opt/papis.nvim/lua/papis/cursor-actions/init.lua:56: in function 'if_ref_valid_run_fun'       
        .../packer/opt/papis.nvim/lua/papis/cursor-actions/init.lua:109: in function <.../packer/opt/papis.nvim/l
ua/papis/cursor-actions/init.lua:108>     
```

The reference is not in the expected format as I had inserted it into another filetype and the copied it over into a different one.
Either way, I suggest that this function should perform three steps:

1. Match reference under cursor against the expected pattern based on filetype, if not successful -> 2
2. Match reference under cursor against all other possible patterns. If successful, notify user that it matched with an unexpected pattern. Else -> 3
3. No match found, fail gracefully by notifying user that no match was found based on the reference pattern

**Comment by maxmahlke** [comment]
Related issue: The `string.find` call always fails for `org` filetypes as the `cite_format_prefix` contains a `[` (full value is `[cite:@`) and is therefore interpreted as malformed pattern as shown in the traceback above. The bracket has to be escaped as `%[`. This of course has to be done for all magic characters. If my lua skills were better, I'd submit a PR.

**Comment by jghauser** [comment]
Thanks for this, I'll have a look!

I'm not sure whether papis.nvim should check whether there are matches for different file formats. I feel like such wrong formatting should be dealt with by language servers, linters, etc. Do you have some particular reason why you think papis.nvim should check for this? (My thinking is that you'll have to fix the citation anyway, so why not just tell the user that there isn't a valid ref key and leave it at that?)

 I do definitely agree that failures should always be graceful and accompanied by useful notifications.

**Comment by maxmahlke** [comment]
My thinking is that it comes at little to no cost computation wise but it offers a degree of freedom to the user. But I also see that this approach may lead to unstable terrain, a reference in a given filetype should be properly formatted. So if `papis.nvim` just fails gracefully and informs the user of the issue that's probably a better way to handle it.

**Comment by maxmahlke** [comment]
Now that I'm looking at the reference key formats per filetype, for `tex`, it's `\cite{refkey}`. `\citep` and `\citet` should also be accepted in my opinion. I only use those two ;-)

**Comment by jghauser** [comment]
Ok, I think i'm  gonna go with just informing the user when we encounter a badly formatted reference. In that case, I think your error stems only from the missing escape of the magic character. I'm gonna fix this tomorrow.

Good point that there can be multiple citation styles. I think I'll probably allow tables as values in the `cite_formats` table so that the first item can be used when inserting a reference, whereas the others will also be used when trying to identify references under the cursor.

And now that I think of it, I have no idea if we correctly handle cases where there's multiple references in one citation. :thinking:

**Comment by maxmahlke** [comment]
For `tex` it should suffice to grab everything inside the curly braces in `word_under_cursor` and split by `,` to get a list in case of multiple citations. This should cover the most common cases like `\cite`, `\citep`, `\cite[][cf.]`. I cannot think of a case where the `refkey` is not the only content of the curly braces.

**Comment by jghauser** [comment]
This should now sort of work as it should. It took a bit longer as my week's been busier than expected and I'm trying to now add tests to everything as well as I fix things.

It should now:
- find references in org files
- find refernces with the alternative syntax in tex files

However, orgmode citation with multiple references may still fail if you're not on the first reference. I'll get to this soon.

**Comment by jghauser** [comment]
Alright, this should all be fixed now. Feel free to re-open if you find any issues! :)

**Comment by maxmahlke** [comment]
It works for `org` and the basic `tex` commands, it fails for something like `\cite[\eg][]{myref}`. But I'd say 90% of the use cases are covered.

Another filetype to add would be the `.bib` files themselves, so

- Add pattern for `bib`
- Add more general pattern for `tex`
- Add support for multiple references

If you don't mind, I could take this as opportunity to learn some more lua and submit a PR for these points soon.

BTW Quickly opening the corresponding pdf/note when the cursor is on a reference is something I never knew I really wanted, it's super cool.

**Comment by jghauser** [comment]
Sure, I'd be very happy about PRs! If you need any help or pointers, do let me know. It shouldn't really require anything except adjusting/adding patterns to the `config.lua`.

What do you mean with "support for multiple references"? For the `cursor-actions` methods to work in citations with multiple references? I thought this should work now. Though it's definitely possible I've missed something...

> BTW Quickly opening the corresponding pdf/note when the cursor is on a reference is something I never knew I really wanted, it's super cool.

Thanks! That's one thing I've been missing for a while; great to hear others find it useful too! :)

Also, maybe you could open another issue about adding/fixing these patterns. Just so issues are kept a bit separate :)
