### ISSUE TITLE
Icons are shown in picker even if `enable_icons=false` is set

### ISSUE THREAD

**Issue by maxmahlke** [jghauser/papis.nvim#79]
Using the following setup, I still see the icons in front of every line in the `telescope` picker. This is straight from the docs, so I believe this should work.

 ```
 require("papis").setup({
    enable_icons = false,
  })
```

I synced the repo just now and the issue persists.

**Comment by jghauser** [comment]
Thanks! Yeah this should work. Will have a look later :)

**Comment by jghauser** [comment]
Hmm, it seems to work for me:
![2024-06-21T15:23:52,530332038+02:00](https://github.com/jghauser/papis.nvim/assets/10319377/ffd8790e-98e7-46c0-9cb7-3a6bf73e149c)
![2024-06-21T15:23:20,351746758+02:00](https://github.com/jghauser/papis.nvim/assets/10319377/882eb71e-02c3-4f52-8e4e-631efa27d120)

**Comment by maxmahlke** [comment]
Odd, for me, I still see the actual symbols. I'm on nvim version `v0.10.0`. Adding the `results_format` also has no effect. I'm using `:Telescope papis` to open the picker.
![Screenshot from 2024-06-21 15-44-06](https://github.com/jghauser/papis.nvim/assets/19716714/599f34c4-68fc-44ec-9889-7ab60151477e)

**Comment by jghauser** [comment]
That is odd indeed. `results_format` is a part of the `search` config, so you will need to actually set `search.results_format` to the value. But that doesn't explain why `enable_icons = false` doesn't work :thinking:

**Comment by jghauser** [comment]
Ooooh, i think I know what might be up! Can you try a `:Papis reload data`? The Telescope lines are precomputed and papis.nvim isn't smart enough to detect when it needs re-init them.

**Comment by maxmahlke** [comment]
Yes, that was it! It correctly hid the icons with only `enable_icons = false` and then, with the correct placement of the `results_format` section, it removed that info entirely after `:Papis reload data`. Thanks!
