### ISSUE TITLE
Trouble running package on macos (apple silicon)

### ISSUE THREAD

**Issue by avonmoll** [jghauser/papis.nvim#82]
I had a working setup on my previous intel-based macos. Since migrating to the new machine, I cannot get `papis.nvim` to work. One thing that was necessary at some point was to install an `arm64`-specific version of `sqlite3`. Previously, I had in my config:

```lua
 vim.g.sqlite_clib_path = "/Users/.../homebrew/opt/sqlite/bin/sqlite3"
```

but running `:checkhealth papis` showed that it couldn't find the associated library, so I switched to

```lua
vim.g.sqlite_clib_path = "/Users/.../homebrew/opt/sqlite/lib/libsqlite3.dylib"
```

Now, running `:checkhealth papis` shows

```
papis: require("papis.health").check()

- ERROR Failed to run healthcheck for "papis" plugin. Exception:
  .../.local/share/nvim/lazy/papis.nvim/lua/papis/health.lua:26: attempt to index field 'data' (a nil value)
```

I went ahead and deleted the previous `papis_db` folder from `~/.local/share/nvim` in case that folder (copied from previous mac) was causing issues. So it looks like something in the `papis/sqlite-wrapper.lua` file isn't running correctly, but that's about all I can figure out on my end.

**Comment by jghauser** [comment]
Thanks for the report! First, are you sure that papis.nvim has been loaded before you ran `:checkhealth papis`. I get your error if I run `checkhealth` before papis.nvim is loaded by a configured filetype. This in itself is a problem, but I don't think it is related to your main issue. Second, can you try running papis.nvim with the debug module (as described in the README) and check if the log has any pointers to where things fail? I doubt it will as the issue seems to be with the `sqlite.lua` dependency, but it doesn't hurt to be sure :).

**Comment by avonmoll** [comment]
Firstly, I updated papis.nvim. Then, I enabled the `debug` module by including `enable_modules = { ["debug"] = true}` to my setup function. Now I get this error when I run `:checkhealth papis`:


```
E5009: Invalid $VIMRUNTIME: /Users/me/share/nvim/runtime                                                                                                   
Error executing lua: /Users/me/share/nvim/runtime/lua/vim/health.lua:346: FileType Autocommands for "checkhealth": Vim(append):Error executing lua callback:
 ...me/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'yaml' language, see :help treesitter-parsers                                     
stack traceback:                                                                                                                                                  
        [C]: in function 'error'                                                                                                                                  
        ...me/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'                                                                        
        ...me/share/nvim/runtime/lua/vim/treesitter/query.lua:250: in function 'fn'                                                                         
        ...rs/me/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'parse'                                                                       
        ...are/nvim/lazy/papis.nvim/lua/papis/completion/source.lua:36: in main chunk                                                                             
        [C]: in function 'require'                                                                                                                                
        ...share/nvim/lazy/papis.nvim/lua/papis/completion/init.lua:22: in function 'setup'                                                                       
        ...me/.local/share/nvim/lazy/papis.nvim/lua/papis/init.lua:89: in function 'start'                                                                       
        ...me/.local/share/nvim/lazy/papis.nvim/lua/papis/init.lua:20: in function <...me/.local/share/nvim/lazy/papis.nvim/lua/papis/init.lua:18>              
        [C]: in function 'setfiletype'                                                                                                                            
        /Users/me/share/nvim/runtime/lua/vim/health.lua:346: in function '_check'                                                                           
        [string "<nvim>"]:1: in main chunk                                                                                                                        
stack traceback:                                                                                                                                                  
        [C]: in function 'setfiletype'                                                                                                                            
        /Users/me/share/nvim/runtime/lua/vim/health.lua:346: in function '_check'                                                                           
        [string "<nvim>"]:1: in main chunk
```

I noticed it said that I didn't have the parser for `yaml` installed so I ran `:TSInstall yaml`. Now, when I run health check for papis it says: `Failed to load parser for language 'yaml': uv_dlopen: no error`. I have been wrestling with a very similar error  with the `norg` parser (see [related issue](https://github.com/nvim-neorg/neorg/issues/1473)). Anyhow, I don't think papis.nvim is ever properly loaded since I don't have access to any of the `:Papis` commands (though I verified that Lazy is loading the package). Maybe my issues stem from a problem with `nvim-treesitter`, but I'm not sure how to proceed.
